name: seqtrack
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.0
  - cudatoolkit=11.3
  - numpy=1.23.5
  - pip=22.3.1
  - pip:
    - huggingface_hub>=0.14.1
    - datasets>=2.12.0
    - opencv-python>=4.7.0.72
    - pandas>=2.0.1
    - matplotlib>=3.7.1
    - tqdm>=4.65.0
    - PyYAML>=6.0
    - tensorboard>=2.13.0
    - timm>=0.6.13
    - yacs>=0.1.8
    - easydict>=1.10
    - einops>=0.6.1
    - thop>=0.1.1.post2209072238
